name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Publish to PyPI?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish Source Distribution
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.publish_to_pypi == 'true' && 'pypi' || 'testpypi' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools build

      - name: Build source distribution
        run: |
          python -m build --sdist
          ls -la dist/

      - name: Publish to PyPI
        if: github.event.inputs.publish_to_pypi == 'true' || github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Publish to Test PyPI
        if: github.event.inputs.publish_to_pypi == 'false' && github.event_name != 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publication summary
        run: |
          target="${{ github.event.inputs.publish_to_pypi == 'true' && 'PyPI' || 'Test PyPI' }}"
          if [ "${{ github.event_name }}" = "release" ]; then
            target="PyPI"
          fi
          echo "✅ Successfully published source distribution to $target"
          echo ""
          echo "📦 Published packages:"
          ls -lh dist/
